config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    require 'sidekiq/web'
    authenticate :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'home#cabinet'

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }

  resources :games, only: ['create']

  get '/rating', to: 'ratings#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :games

  monetize :amount_cents, with_model_currency: :amount_currency,
                          as: :amount,
                          numericality: { greater_than_or_equal_to: 0 }
end

app/models/app_error.rb
class AppError < ApplicationRecord
  has_many :game_errors
  has_many :games, through: :game_errors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency_exchange.rb
class CurrencyExchange < ApplicationRecord
  include ActiveRecord::Singleton

  BASE_CURRENCY = 'EUR'.freeze
end

app/models/game.rb
class Game < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :account
  has_many :ratings, dependent: :destroy
  has_many :game_errors
  has_many :app_errors, through: :game_errors

  validates :bet_amount_cents, numericality: { greater_than: 0 }
  validates :win_amount_cents, numericality: { greater_than_or_equal_to: 0 }

  scope :last_twenty, -> { order(created_at: :desc).first(20) }

  monetize :bet_amount_cents, as: :bet_amount,
                              with_model_currency: :bet_amount_currency
  monetize :win_amount_cents, as: :win_amount,
                              with_model_currency: :win_amount_currency

  aasm column: 'status' do
    state :pending, initial: true
    state :failure, :in_validation, :in_progress, :done

    event :fail do
      transitions from: [:pending, :in_progress, :in_validation], to: :failure
    end

    event :run_validation do
      transitions from: :pending, to: :in_validation
    end

    event :proceed do
      transitions from: :in_validation, to: :in_progress
    end

    event :complete do
      transitions from: :in_progress, to: :done
    end
  end
end

app/models/game_error.rb
class GameError < ApplicationRecord
  belongs_to :game
  belongs_to :app_error
end

app/models/game_service.rb
class GameService < ApplicationRecord
  include ActiveRecord::Singleton

  monetize :revenue_amount_cents, as: :revenue_amount,
                                  with_model_currency: :revenue_amount_currency
end

app/models/rating.rb
class Rating < ApplicationRecord
  RATING_TOP_AMOUNT = 10

  belongs_to :game

  scope :top, -> { limit(RATING_TOP_AMOUNT).order(score_cents: :desc) }

  monetize :score_cents, as: :score,
                         with_model_currency: :score_currency
end

app/models/user.rb
class User < ApplicationRecord
  has_many :accounts
  has_many :games

  after_create :create_account_for_user

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  def ordered_accounts
    accounts.order(amount_currency: :asc)
  end

  def accounts_hash
    ordered_accounts.each_with_object({}) do |account, hash|
      hash[account.id] = {
        id: account.id,
        amount: account.amount.format,
        amount_currency: account.amount.currency.iso_code
      }
      hash
    end
  end

  private

  def create_account_for_user
    %w[EUR USD RUB].each do |currency|
      accounts.create!(amount_cents: 1_000_000, amount_currency: currency)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/concerns/for_cable.rb
module ForCable
  def set_current_user_for_action_cable
    cookies.signed[:user_id] = current_user&.id
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
    @accounts = current_user.accounts
  end

  def create
    @game = current_user.games.build(game_params)
    @game.bet_amount_currency = @game.account.amount_currency

    if @game.save
      connection.success(@game)
      Games::BaseService.new(@game).start
    else
      connection.failure
    end
  end

  private

  def connection
    Games::ActionCableConnections.instance.connection(current_user.id)
  end

  def game_params
    params.require(:game).permit(:bet_amount_cents, :account_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def cabinet
    @user = current_user
    @games = current_user.games.last_twenty
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @top_wins = Rating.top
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  include ForCable

  def create
    super
    set_current_user_for_action_cable
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  include ForCable

  def create
    set_current_user_for_action_cable
    super
  end

  def destroy
    cookies.signed[:user_id] = ''
    super
  end
end

app/helpers/account_helper.rb
module AccountHelper
  def accounts_select(accounts)
    accounts.map do |ac|
      {
        value: ac.id,
        label: "#{ac.amount.currency} - (Balance: #{ac.amount.format})"
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def authentication_buttons
    if user_signed_in?
      content_tag :li, class: 'nav-item' do
        link_to 'Sign out', destroy_user_session_path,
          method: :delete, class: 'nav-link'
      end
    else
      content = content_tag :li, class: 'nav-item' do
        link_to 'Sign up', new_user_registration_path, class: 'nav-link'
      end
      content << content_tag(:li, class: 'nav-item') do
        link_to 'Sign in', new_user_session_path, class: 'nav-link'
      end
    end
  end
end

app/helpers/game_helper.rb
module GameHelper
  def game_revenue(bet_amount, win_amount)
    win_amount - bet_amount
  end

  def win_background(bet_amount, win_amount)
    revenue = game_revenue(bet_amount, win_amount)

    if revenue.positive?
      'tag-success'
    elsif revenue.zero?
      'tag-primary'
    else
      'tag-danger'
    end
  end

  def status_color(status)
    case status
    when 'pending' then 'info'
    when 'in_validation' then 'warning'
    when 'in_progress' then 'primary'
    when 'done' then 'success'
    when 'failure' then 'danger'
    end
  end
end

app/views/games/_accounts_select.slim
select.form-control.accounts-select id='account_id' name='account_id' required=true
  - accounts_select(accounts).each do |account|
    option class="account-#{account[:value]}" value=account[:value] #{account[:label]}

app/views/games/_form.slim
.row
  form.new-game-form
    .col-xs-3
      label for='bet_amount_cents' Enter bet
      input.form-control type='number' id='bet_amount_cents' name='bet_amount_cents' required=true

    .col-xs-6
      label for='account_id' Select your account
      = render 'games/accounts_select', accounts: current_user.ordered_accounts

    .col-xs-3
      label Click for submit
      button.btn.btn-success.submit-new-game type='submit' Submit bet

app/views/games/_game.slim
tr class="game-row-#{game.id}"
  th.id-col = game.id

  th.bet-col
    = game.bet_amount
    '
    = game.bet_amount_currency

  th.win-col
    - if game.done?
      = game.win_amount
      '
      = game.win_amount_currency
      '
      span.tag class="#{win_background(game.bet_amount, game.win_amount)}"
        = " (#{game_revenue(game.bet_amount, game.win_amount)} #{game.win_amount_currency}) "

    - elsif game.failure?
      - game.app_errors.each do |error|
        span.tag.tag-danger = error.message
        br

  th.status-col
    span class="tag tag-#{status_color(game.status)}" = game.status

app/views/games/_games.slim
table.table.game-table
  thead
    tr
      th Id
      th Bet amount
      th Win amount / Error
      th Status

  tbody
    - @games.each do |game|
      = render 'games/game', game: game

app/views/home/_accounts_list.slim
ul.list-group.list-group-flush.accounts-list
  - accounts.each do |account|
    li.list-group-item class="account-#{account.id}"
      = account.amount.format

app/views/home/cabinet.slim
.game-block.col-xs-9
  .col-xs-12.m-b-2
    h4 Game form
    = render 'games/form'

  .col-xs-12
    h4 Last games
    = render 'games/games'

.accounts-block.col-xs-3.pull-xs-right
  .card
    .card-header Accounts
    = render 'home/accounts_list', accounts: @user.accounts

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title GameServer
    script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-dark.bg-inverse
      button.navbar-toggler.hidden-sm-up aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label=("Toggle navigation") data-target="#exCollapsingNavbar2" data-toggle="collapse" type="button" 
        | ☰
      #exCollapsingNavbar2.collapse.navbar-toggleable-xs
        = link_to 'GameServer', root_path, class: 'navbar-brand'
        ul.nav.navbar-nav
          li.nav-item
            = link_to 'Rating', rating_path, class: 'nav-link'

        ul.nav.navbar-nav.pull-xs-right
          = authentication_buttons

    .content
      = yield

app/views/ratings/_win.slim
tr
  th.win-col
    = win.game.user.email
  th.bet-col
    = win.score
    '
    = win.score_currency

app/views/ratings/index.slim
.col-xs-12
  h4 Top wins
  table.table.game-table
    thead
      tr
        th Email
        th Win amount

    tbody
      = render partial: 'win', collection: @top_wins